name: web2wave
description: Web2Wave is a lightweight Flutter package that provides a simple interface for managing user subscriptions and properties through a REST API.
version: 1.0.0
repository: https://github.com/web2wave/web2wave_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
