name: web2wave
description: Web2Wave is a lightweight Flutter package that provides a simple interface for managing user subscriptions and properties through a REST API.
version: 1.0.0
repository: https://github.com/web2wave/web2wave_flutter
homepage: https://web2wave.com
issue_tracker: https://github.com/web2wave/web2wave_flutter/issues
documentation: https://github.com/web2wave/web2wave_flutter
topics:
  - web2app
  - web2wave

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  webview_flutter: ^4.10.0

dev_dependencies:
  dotenv: ^4.2.0
  lints: ^3.0.0
  test: ^1.24.0
