name: Publish to pub.dev

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  # bump_version:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Extract version from tag
  #       id: get_version
  #       run: |
  #         TAG=${GITHUB_REF#refs/tags/v}
  #         echo "version=$TAG" >> "$GITHUB_OUTPUT"

  #     - name: Checkout main branch
  #       uses: actions/checkout@v3
  #       with:
  #         ref: main

  #     - name: Set up Git
  #       run: |
  #         git config user.name "github-actions"
  #         git config user.email "github-actions@github.com"

  #     - name: Update pubspec.yaml version
  #       run: |
  #         sed -i "s/^version:.*/version: ${{ steps.get_version.outputs.version }}/" pubspec.yaml

  #     - name: Commit and push version update
  #       run: |
  #         git add pubspec.yaml
  #         git commit -m "chore: set pubspec version to ${{ steps.get_version.outputs.version }}" || echo "No changes to commit"
  #         git push origin main

  publish:
    # needs: bump_version
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
